parts_of_speech_mapping = {
    'Adjective': 'adjective', 
    'Adverb': 'adverb',
    'Ambiposition': 'ambiposition',
    'Article': 'article',
    'Circumposition': 'circumposition',
    'Classifier': 'classifier',
    'Conjunction': 'conjunction',
    'Contraction': 'contraction',
    'Counter': 'counter',
    'Determiner': 'determiner',
    'Ideophone': 'ideophone',
    'Interjection': 'interjection',
    'Noun': 'noun',
    'Numeral': 'numeral',
    'Participle': 'participle',
    'Particle': 'particle',
    'Postposition': 'postposition',
    'Preposition': 'preposition',
    'Pronoun': 'pronoun',
    'Proper noun': 'proper_noun',
    'Verb': 'verb',
    'Circumfix': 'circumfix',
    'Combining form': 'combining_form',
    'Infix': 'infix',
    'Interfix': 'interfix',
    'Prefix': 'prefix',
    'Root': 'root',
    'Suffix': 'suffix',
    'Diacritical mark': 'diacritical_mark',
    'Letter': 'letter',
    'Ligature': 'ligature',
    'Number': 'number',
    'Punctuation mark': 'punctuation_mark',
    'Syllable': 'syllable',
    'Symbol': 'symbol',
    'Phrase': 'phrase',
    'Proverb': 'proverb',
    'Prepositional phrase': 'prepositional_phrase',
    'Han character': 'han_character',
    'Hanzi': 'hanzi',
    'Kanji': 'kanji',
    'Hanja': 'hanja',
    'Romanization': 'romanization'
}